.TH "Referencia del directorio includes" 3 "Domingo, 7 de Mayo de 2017" "Redes 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio includes \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBG\-2311\-01\-P1_general\&.h\fP"
.br
.RI "\fI: Funciones del módulo general \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P1_semaforos\&.h\fP"
.br
.RI "\fIUtilidades para el uso de semaforos\&. \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P1_server\&.h\fP"
.br
.RI "\fI: Funciones del módulo server \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P1_server_funciones\&.h\fP"
.br
.RI "\fI: Funciones del módulo server funciones \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P1_socket\&.h\fP"
.br
.RI "\fI: Funciones del módulo socket \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P1_utils\&.h\fP"
.br
.RI "\fI: Funciones del módulo utils \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P2_client\&.h\fP"
.br
.RI "\fI: Funciones del módulo client \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P2_client_funciones\&.h\fP"
.br
.RI "\fI: Funciones del módulo client funciones \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P2_client_funciones_user\&.h\fP"
.br
.RI "\fI: Funciones del módulo client funciones user \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P3_echo_cliente\&.h\fP"
.br
.RI "\fI: Funciones del módulo cliente echo \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P3_echo_server\&.h\fP"
.br
.RI "\fI: Funciones del módulo servidor echo \fP"
.ti -1c
.RI "archivo \fBG\-2311\-01\-P3_ssl\&.h\fP"
.br
.RI "\fI: Funciones del módulo SSL \fP"
.in -1c
