.TH "includes/G-2311-01-P1_socket.h" 3 "Domingo, 7 de Mayo de 2017" "Redes 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/G-2311-01-P1_socket.h \- : Funciones del módulo socket  

.SH SYNOPSIS
.br
.PP
\fC#include 'G\-2311\-01\-P1_general\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBdaemonizar\fP (char *servicio)"
.br
.ti -1c
.RI "int \fBcrear_socket\fP (int protocolo)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
: Funciones del módulo socket 


.PP
\fBAutor:\fP
.RS 4
Oscar Garcia de Lara Parreño & Santiago Gomez Aguirre\&. Grupo: 2311 
.RE
.PP
\fBFecha:\fP
.RS 4
07-05-2017 
.RE
.PP

.PP
Definición en el archivo \fBG\-2311\-01\-P1_socket\&.h\fP\&.
.SH "Documentación de las funciones"
.PP 
.SS "int crear_socket (int protocolo)"
crear_socket  crear_socket 
.PP
\fBParámetros:\fP
.RS 4
\fIprotocolo\fP Protocolo para indicar si se quiere TCP o UDP 
.RE
.PP
\fBDevuelve:\fP
.RS 4
el socket o -1 en caso de error 
.RE
.PP

.SS "int daemonizar (char * servicio)"
daemonizar un programa  daemonizar 
.PP
\fBParámetros:\fP
.RS 4
\fIservicio\fP Nombre del proceso 
.RE
.PP
\fBDevuelve:\fP
.RS 4
-1 en caso de error 
.RE
.PP

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes 2 del código fuente\&.
