.TH "includes/G-2311-01-P1_general.h" 3 "Domingo, 7 de Mayo de 2017" "Redes 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
includes/G-2311-01-P1_general.h \- : Funciones del módulo general  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <sys/select\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <netdb\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <net/if\&.h>\fP
.br
\fC#include <sys/ioctl\&.h>\fP
.br
\fC#include <syslog\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <redes2/irc\&.h>\fP
.br

.SS "'typedefs'"

.in +1c
.ti -1c
.RI "typedef int(* \fBpf_msg\fP) (char *command, int socket)"
.br
.in -1c
.SS "Enumeraciones"
.SH "Descripción detallada"
.PP 
: Funciones del módulo general 


.PP
\fBAutor:\fP
.RS 4
Oscar Garcia de Lara Parreño & Santiago Gomez Aguirre\&. Grupo: 2311 
.RE
.PP
\fBFecha:\fP
.RS 4
07-05-2017 
.RE
.PP

.PP
Definición en el archivo \fBG\-2311\-01\-P1_general\&.h\fP\&.
.SH "Documentación de los 'typedefs'"
.PP 
.SS "typedef int(* pf_msg) (char *command, int socket)"
[int description]  int 
.PP
\fBParámetros:\fP
.RS 4
\fIpf_msg\fP [description] 
.RE
.PP
\fBDevuelve:\fP
.RS 4
[description] 
.RE
.PP

.PP
Definición en la línea 49 del archivo G\-2311\-01\-P1_general\&.h\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes 2 del código fuente\&.
