.TH "IRCInterface" 3 "Domingo, 7 de Mayo de 2017" "Redes 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IRCInterface \- Interface
.SS "Módulos"

.in +1c
.ti -1c
.RI "\fBCallbaks\fP"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes 2 del código fuente\&.
