.TH "param_sendfile" 3 "Domingo, 7 de Mayo de 2017" "Redes 2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
param_sendfile \- 
.SH SYNOPSIS
.br
.PP
.SH "Descripción detallada"
.PP 
Definición en la línea 18 del archivo G\-2311\-01\-P2_client\&.h\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Redes 2 del código fuente\&.
